[[servers]]
host = "news.example.com"
port = 119
name = "Example News Server 1"

[[servers]]
host = "nntp.example.org"
port = 119
name = "Example News Server 2"

[[servers]]
host = "localhost"
port = 1119
name = "Local Test Server"
